### ISSUE TITLE
Models.DocumentTypeExtensions.ToDocumentType() generates error

### ISSUE THREAD

**Issue by mpiesens** [janssenr/SendCloudApi.Net#15]
Hi,

I found an error in the ToDocumentType() function in the Model.Documentype.cs class. 
It gives us a "ToEnumValue(): Invalid description for enum DeliveryOption" error.

On line 39 it says:    var type = typeof(DeliveryOption);
I think DeliveryOption should be DocumentType

**Comment by janssenr** [comment]
Should be fixed now.

**Comment by mpiesens** [comment]
Unforunately I am still getting the error.
I updated the nuget package to version 2.0.14.0
Is this the latest version, including the fix?

**Comment by janssenr** [comment]
2.0.14 should be the latest version.
Do you have a replication procedure for me?
Then I can test the code myself.

**Comment by mpiesens** [comment]
I am trying to create a Parcel, containing 2 ParcelItems, with a shipping adres in London(GB). 
While sending from de Netherlands(NL), this should create a Customs Declaration Form. 
This gives an error on  SendCloudApi.Net.SendCloudApi.Parcels.Create(parcel)
I can view the parcel in Sendcloud, including the Customs Declaration Form, so creation itself seems to work. 

When I create a Parcel for shipping inside the EU, so no Customs Declaration Form is created, it al works fine and I am able to print the label.

**Comment by janssenr** [comment]
Can you sent me a code example which results in the Error?

**Comment by mpiesens** [comment]
private async void createParcel()
{
    var sendCloudClient = new SendCloudApi.Net.SendCloudApi(apiKey, apiSecret);

    var parcel = new CreateParcel
    {
        Name = "Mano Test",
        Address = "Downingstreet",
        HouseNumber = "10",
        City = "London",
        PostalCode = "SW1A 2AA",
        Country = "GB",
        RequestLabel = true,
        ApplyShippingRules = true,
        ShippingMethod = (int)enumShipMethod.DeutschePost,
        OrderNumber = "12345",
        AddressDivided = new AddressDivided()
        {
            Street = "Downingstreet",
            HouseNumber = "10"
        },
        Telephone = "",
        Email = "",
        CountryState = "",
        CustomsInvoiceNr = "12345",
        CustomsShipmentType = CustomsShipmentType.CommercialGoods,
        Weight = 0.470
    };

    parcel.ParcelItems = new ParcelItem[]{
        new ParcelItem()
        {
            Description = "T-shirt - Arnhem Rolls",
            Quantity = 1,
            Weight = 0.235,
            Value = 39.95,
            HarmonizedSystemCode = "61091000",
            OriginCountry = "NL",
            StockKeepingUnit = "0264.M.T.009B.O.XL",
            ProductId = "PROD-B23CQ6"
        },
        new ParcelItem()
        {
            Description = "T-shirt - The Sky Is The Limit",
            Quantity = 1,
            Weight = 0.235,
            Value = 39.95,
            HarmonizedSystemCode = "61091000",
            OriginCountry = "NL",
            StockKeepingUnit = "0327.M.T.029.O.XXXL",
            ProductId = "PROD-C2PK2C"
        }
    };

    try
    { 
        var response = await sendCloudClient.Parcels.Create(parcel);
    }
    catch (SendCloudApi.Net.Exceptions.SendCloudException e)
    {
        throw new Exception(e.Message);
    }

}

**Comment by janssenr** [comment]
I think it was related to a typo fix which I fixed today.
A typo in commercial-invoice (different dash).
Can you update to NuGet package 2.0.16 and check if your issue is solved?

**Comment by janssenr** [comment]
There was also a typo in cn23-default (different dash).
Can you please try version 2.0.17?

**Comment by mpiesens** [comment]
Yes, that was it! It is working fine now!
Thank you very much!
